Add handler delegates
linksplatform/Data pull request #90
Opened 2021-12-26 15:52 UTC by FreePhoenix888

- Remove unused code and update XML Documentation
- Repair XML Documentation
- Add handler delegates
- Use WriteHandler
- Use ReadHandler

2021-12-26 16:22 UTC, Konard requested changes

2021-12-27 13:37 UTC, FreePhoenix888 commented on csharp/Platform.Data/ReadHandler.cs
> +public delegate TLink ReadHandler<TLink>(IList<TLink> restriction);
We'll deviate from style this way

2021-12-27 13:38 UTC, uselessgoddess commented on csharp/Platform.Data/ReadHandler.cs
> +public delegate TLink ReadHandler<TLink>(IList<TLink> restriction);
```suggestion
public delegate TLink ReadHandler<TLink>(IList<TLink>);
```

2021-12-27 13:38 UTC, FreePhoenix888 commented on csharp/Platform.Data/WriteHandler.cs
> +public delegate TLink WriteHandler<TLink>(IList<TLink> restriction, IList<TLink> substitution);
We'll deviate from our style this way, will not we?

2021-12-27 13:39 UTC, FreePhoenix888 commented on csharp/Platform.Data/ReadHandler.cs
> +public delegate TLink ReadHandler<TLink>(IList<TLink> restriction);
@uselessgoddess amazing

2021-12-27 13:45 UTC, Konard approved these changes

2021-12-27 13:45 UTC, merged